spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    username: mohamed.hamma

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080