spring:
  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://db:5432/eventdb7
    username: mohamed.hamma
    password: secret

  sql:
    init:
      mode: never

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    jdbc:
      repositories:
        enabled: true

logging:
  level:
    org.flywaydb: INFO

server:
  port: 8080