spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 100

  datasource:
    url: jdbc:postgresql://db:5432/eventdb
    username: mohamed.hamma
    password: secret

  sql:
    init:
      mode: never # Spring N'EXECUTE PAS schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org.flywaydb: DEBUG

server:
  port: 8080