debug: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${EXPIRATION}

  pagination:
    default-page-size: ${PSIZE}
    max-page-size: ${MAXPSIZE}

  security:
    max-login-attempts: ${MAXATTEMPTS}

  cache:
    ttl-minutes: ${TTLMINUTES}

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  datasource:
    url: ${URLDB}
    username: ${USERDB}
    password: ${SECRET}

  jpa:
    pen-in-view: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: ${DDLAUTO}
    show-sql: true

  data:
    jdbc:
      repositories:
        enabled: true

  sql:
    init:
      mode: never