spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://db:5432/eventdb
    username: mohamed.hamma
    password: secret

  sql:
    init:
      mode: always # OBLIGATOIRE : Dit à Spring d'exécuter le fichier schema.sql

  jpa:
    hibernate:
      ddl-auto: none # OBLIGATOIRE : Empêche Hibernate d'écraser vos tables
    show-sql: true
  logging:
    level:
      org.flywaydb: DEBUG

server:
  port: 8080