spring:
  application:
    name: eventProject-local
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    username: mohamed.hamma
    password: secret

  sql:
    init:
      mode: always # OBLIGATOIRE : Dit à Spring d'exécuter le fichier schema.sql

  jpa:
    hibernate:
      ddl-auto: update # OBLIGATOIRE : Empêche Hibernate d'écraser vos tables
    show-sql: true

server:
  port: 8080